// Note: If PostgresDialect is not available from 'kysely', install @kysely/pg:
// npm install @kysely/pg
// and change the import to: import { PostgresDialect } from '@kysely/pg';
import { Kysely, PostgresDialect, Generated, ColumnType, JSONColumnType } from 'kysely';
import { Pool } from 'pg';

// Global type for Next.js hot reloading
declare global {
  // eslint-disable-next-line no-var
  var _kyselyDb: Kysely<Database> | undefined;
}

// Site table interface
export interface SiteTable {
  id: Generated<string>; // UUID generated by DB
  user_id: string; // References users.id (UUID)
  subdomain: string; // Unique
  custom_domain: string | null; // Unique, nullable
  settings: JSONColumnType<Record<string, unknown>>; // JSONB settings
  created_at: ColumnType<Date, string | undefined, never>; // timestamp with timezone
  updated_at: ColumnType<Date, string | undefined, never>; // timestamp with timezone
}

// Page table interface
export interface PageTable {
  id: Generated<string>; // UUID
  site_id: string; // References sites.id (UUID)
  slug: string; // Unique per site
  title: string;
  content: JSONColumnType<Record<string, unknown>>; // JSONB content
  published: boolean;
  created_at: ColumnType<Date, string | undefined, never>; // timestamp with timezone
  updated_at: ColumnType<Date, string | undefined, never>; // timestamp with timezone
}

// Database interface
export interface Database {
  sites: SiteTable;
  pages: PageTable;
  // Add other tables here as needed
  // users: UserTable;
}

// Create database connection
function createDatabase(): Kysely<Database> {
  if (!process.env.DATABASE_URL) {
    throw new Error('DATABASE_URL environment variable is not set');
  }

  // Parse connection string and ensure SSL is properly configured
  const connectionString = process.env.DATABASE_URL;
  
  // Check if using Supavisor (pooler) connection - these use IPv4
  const isPoolerConnection = connectionString.includes('pooler.supabase.com');
  
  // For pooler connections, disable SSL completely to avoid SCRAM SASL issues
  // Supavisor pooler handles encryption at the proxy level
  let cleanConnectionString = connectionString;
  if (isPoolerConnection) {
    // Remove existing sslmode/uselibpqcompat if present
    const baseUrl = connectionString.split('?')[0];
    // Disable SSL for pooler connections
    cleanConnectionString = `${baseUrl}?sslmode=disable`;
  } else {
    // Remove any existing sslmode parameter for direct connections
    cleanConnectionString = connectionString.split('?')[0];
  }
  
  const pool = new Pool({
    connectionString: cleanConnectionString,
    // SSL configuration
    // For pooler connections: SSL disabled (handled by proxy)
    // For direct connections: use SSL with certificate verification
    ...(isPoolerConnection
      ? {} // SSL disabled via sslmode=disable in connection string
      : {
          ssl: {
            rejectUnauthorized: true, // Direct connections use valid certificates
          },
        }),
    // Optional: tune pool settings
    max: 10, // Maximum number of clients in the pool
    idleTimeoutMillis: 30000, // Close idle clients after 30 seconds
    connectionTimeoutMillis: 2000, // Return an error after 2 seconds if connection could not be established
  });

  return new Kysely<Database>({
    dialect: new PostgresDialect({
      pool,
    }),
  });
}

// Export singleton database instance
export const db: Kysely<Database> = (() => {
  // In production, always create a new instance
  if (process.env.NODE_ENV === 'production') {
    return createDatabase();
  }

  // In development, use global variable to avoid creating multiple pools during hot reloads
  if (!global._kyselyDb) {
    global._kyselyDb = createDatabase();
  }

  return global._kyselyDb;
})();

// Helper types for type-safe queries
export type Site = SiteTable;
export type Page = PageTable;
export type NewSite = Omit<SiteTable, 'id' | 'created_at' | 'updated_at'>;
export type NewPage = Omit<PageTable, 'id' | 'created_at' | 'updated_at'>;
export type SiteUpdate = Partial<Omit<SiteTable, 'id' | 'created_at'>>;
export type PageUpdate = Partial<Omit<PageTable, 'id' | 'created_at'>>;
